# Generated by Django 4.0.4 on 2022-04-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.questionnaire'),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('question', 'response')},
        ),
    ]
