# Generated by Django 4.0.4 on 2022-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_question_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='answer_integer',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer_text',
            field=models.TextField(null=True),
        ),
    ]
